// Generated by https://quicktype.io

export interface Product {
  id:       string;
  c_title:  string;
  c_detail: string;
  c_date:   Date;
  c_view:   string;
  c_color:  string;
  c_pic:    string;
}
